FROM ztapir/graalvm-ce:20.1.0-java11 as builder

WORKDIR /app
COPY . /app

RUN curl -L -o musl.tar.gz https://github.com/gradinac/musl-bundle-example/releases/download/v1.0/musl.tar.gz && \
    tar -xvzf musl.tar.gz

RUN ./sbt graalvm-native-image:packageBin

FROM scratch

EXPOSE 8080

COPY --from=builder /app/target/graalvm-native-image/zio-api /zio-api

ENTRYPOINT ["/zio-api"]