FROM ztapir/graalvm-ce:20.3.0-java11 as builder

WORKDIR /app
COPY . /app

RUN ./sbt graalvm-native-image:packageBin

RUN upx -7 /app/target/graalvm-native-image/zio-tapir-api

FROM scratch

EXPOSE 8080

COPY --from=builder /app/target/graalvm-native-image/zio-tapir-api /zio-tapir-api

ENTRYPOINT ["/zio-tapir-api"]