name: Scala CI

on:
  push:
    branches: [ rychlkat/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image
      run: docker build . -t rychlkat/graalvm-ce:20.3.0-java11 -f Dockerfile.prebuild.graalvm
    - run: echo "Base image built with tag rychlkat/graalvm-ce:20.3.0-java11"
    
